export { default as FlagList } from './Countries/FlagList.vue'
export { default as Login } from './Auth/Login.vue'
export { default as Logout } from './Auth/Logout.vue'
export { default as UserProfile } from './Auth/UserProfile.vue'
export { default as Header } from './Page/Header.vue'
export { default as Footer } from './Page/Footer.vue'
